### ISSUE TITLE
New Text for Website Feb 23 2015

### ISSUE THREAD

**Issue by chipstehr** [getlantern/www.getlantern.org#56]
Hey below is the new text for the website

LANTERN HOME PAGE

An app to end Internet censorship. 
Internet censorship hurts all of us, but we can stop it. Lantern is the app you install on your computer that opens the Internet for everyone.

(Remove Watch Video Link until we have updated video)

DOWNLOAD LANTERN 1.5.17
for
Mac OS X
Available for Mac, Windows, and Linux.
Preview our beta release version ( Version name should be mentioned)
HOW DOES LANTERN WORK?
Lantern's goal is access: creating fast, reliable connections to the open Internet. Lantern uses secure servers and peer access points to provide Internet access to blocked sites.  Lantern is unique because it uses peer connections as a source of Internet connection when servers are unavailable.

QUESTIONS AND ANSWERS

Who Are We?
Lantern is built by the Brave New Software Project, Inc, a registered 501c3 non-profit dedicated to using software to tackle tough global challenges. Brave New Software’s founder and Lantern lead developer, Adam Fisk, was formerly a lead developer of the peer-to-peer file sharing services LimeWire and LittleShoot. While working on these P2P architectures, Adam realized they could be useful in providing unfiltered internet access. You can watch some of Adam’s talks about Lantern here and here.

Is Lantern free? Will running it cost me anything?
Lantern is a free, open source software. It is free to use, modify, and redistribute.
If your Internet connection has a data limit, then giving access through Lantern will be included in your usage. 

Is Lantern safe for me to use?
Lantern encrypts all of the information being sent through its secure servers from your computer to the sites on Lantern’s proxy list, so that censors will not be able to see your traffic to those sites. Remember to always use use HTTPS and ideally to install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere), because then your traffic is always encrypted and not viewable by anyone regardless of how you are accessing the Internet. Like most proxy tools, Lantern cannot prevent the sites that you visit from using cookies, which store your browsing information in them.  Though your traffic is encrypted, Lantern cannot prevent other sites from identifying your IP address or location.

Whenever the peer-to-peer connections are engaged, Lantern cannot ensure that the traffic is viewed because a censor could actually become a peer. As mentioned before, if you use HTTPS, your traffic will not be viewable by anyone.
If you require that the sites you visit do not learn your IP address or physical location (they typically  can, which may come as a surprise), then we recommend you use Tor (link here). In determining which tool to use, if speed and reliability of service are most important to you, Lantern is your tool. If you can tolerate slower speeds to post sensitive information on the Internet, you may want to use Tor. 
For users with unrestricted Internet access in the uncensored world running as access points, Lantern currently allows any traffic through your machine from censored users with blocked Internet. While Lantern uses a default proxied list of sites that it provides access to, blocked users in censored regions can customize that list to go to any site they choose. As an access point, you have no control over those sites.  In future releases of Lantern, those giving access will be able to manage this aspect as well.

What information does Lantern collect about me?
Lantern allows users to choose to provide the Lantern team with useful debugging information as well as analytics, which you can configure in your Lantern settings. If you choose to send Lantern that data, we will not use it for any other purpose other than providing the Lantern service to you and others. 

How does Lantern work if I canʼt reach any users giving access?
To help get the Lantern network started we have set up Lantern Cloud Servers. These channel a significant amount of traffic. This ensures a higher reliability of service by having a variety of sources for Internet access.

What is the Lantern proxied sites list?
Lantern only provides access to blocked sites, and it does this through a default proxied sites list. Therefore, if a web site is unblocked, Lantern will get out of the way and use your regular Internet connection to send you directly to that site. That ensures that users are able to see unblocked content as quickly as possible and also that we don’t waste network resources providing access to content that is  not blocked in the first place.
If you are not getting access to a blocked site, that does not necessarily mean that Lantern is not working. You may need to add that site to our list of blocked sites to get access. You can do this in the settings or send an email to us at team@getlantern.org

My Internet isn’t blocked, how I can I help someone who does have blocked Internet? I live in an uncensored region and donʼt know anyone in a censored region. Can I still help?
Definitely! You can both run Lantern and invite more people to join the cause, even if those people also live in an uncensored region. When you run Lantern, you will  be added to our DNS round-robin so that a small portion of overall traffic gets routed through your machine. While Lantern also runs its own servers to ensure a good quality of service, each user helps reduce that burden. Our ultimate goal is to build a system that bypasses censorship even if we cease to exist as a company, and that is  only possible if a lot of people run it to create new access points. When you invite more people, they will help lighten the load further for everyone.

OK, Iʼve installed Lantern. Now what?
For users in uncensored regions, there are two basic things you can do once youʼve installed Lantern:
— Run Lantern as much as possible.
— Add more users you trust as Lantern friends.
Whenever you run Lantern, you create a new access point users in censored regions can use to access the open Internet. Remember, though, that your own social network is part of what enables Lantern to stay unblocked, so inviting your contacts to join the cause is an important step!

How can I contribute?
Please see Getting Involved.

I have more questions, where do I go?
If you have more technical questions, please see the Developers Q&A. Also feel free to post to the user forums or the developers forum.

**Comment by oxtoacart** [comment]
Suggested changes (look for ~~strikethroughs~~ and **emphasis**).

HOW DOES LANTERN WORK?
Lantern's goal is access: creating fast, reliable connections to the open Internet. Lantern uses ~~secure servers and peer access points~~ **peer access points and secure servers** to provide Internet access to blocked sites. Lantern is unique because it uses peer connections as a source of Internet connection when servers are unavailable.

^ I rewrote this to avoid implying that peer access points are secure, since they're not.

QUESTIONS AND ANSWERS

Is Lantern free? Will running it cost me anything?

Lantern is a free, open source software. It is free to use, modify, and redistribute.
If your Internet connection has a data limit, then giving access through Lantern will ~~be included in~~ **count towards** your usage.

~~Is Lantern safe for me to use?~~
**Is it safe to use Lantern to access the Internet?**
[I suggest rewriting this for brevity, because as it stands (much like on the current site) there is too much too take in. In particular, the distinction between Lantern servers and peer proxies is irrelevant--since we force a portion of everyone's traffic through peer proxies, the system overall is no more secure than the part of the system that uses peers.  We should look to other product warnings (tobacco, alcohol, etc.) for inspiration.]

~~Lantern encrypts all of the information being sent through its secure servers from your computer to the sites on Lantern’s proxy list, so that censors will not be able to see your traffic to those sites. Remember to always use use HTTPS and ideally to install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere), because then your traffic is always encrypted and not viewable by anyone regardless of how you are accessing the Internet. Like most proxy tools, Lantern cannot prevent the sites that you visit from using cookies, which store your browsing information in them. Though your traffic is encrypted, Lantern cannot prevent other sites from identifying your IP address or location.~~

~~Whenever the peer-to-peer connections are engaged, Lantern cannot ensure that the traffic is viewed because a censor could actually become a peer. As mentioned before, if you use HTTPS, your traffic will not be viewable by anyone.~~

Lantern fixes a few of the usual problems that you may encounter when browsing the web. For sites that you visit using Lantern:

* It is harder for 3rd parties like censors or employers to use forged HTTPS certificates to intercept your communications.
* It is harder for 3rd parties to use wifi access points to intercept your communications.
* The sites that you visit cannot determine your IP address and location.

Most of the general rules about safely using the internet still apply when you use Lantern:

* If you don’t want others to see the content that you read and post, use HTTPS and even better install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere).
* Sites can and do use cookies to track your online activity.  Lantern does not prevent this.

In addition to the usual considerations, when you use Lantern it is possible for censors, Team Lantern, and other third parties to:

* Find out that you are using Lantern.
* Learn about some of the sites that you visit using Lantern.

~~If you require that the sites you visit do not learn your IP address or physical location (they typically can, which may come as a surprise), then~~**If you require the ability to use the internet completely anonymously**, we recommend **that** you use Tor (link here). In determining which tool to use, if speed and reliability of service are most important to you, Lantern is your tool. If you can tolerate slower speeds to post sensitive information on the Internet, you may want to use Tor.

**Is it Safe for me to use Lantern to provide access to the Internet?**
For users with unrestricted Internet access in the uncensored world running as access points, Lantern currently allows ~~any traffic through your machine from censored users with blocked Internet~~ **other people to access any site on the internet via your connection, including ones that you may disagree with or that may be illegal in your jurisdiction.** ~~While Lantern uses a default proxied list of sites that it provides access to, blocked users in censored regions can customize that list to go to any site they choose. As an access point, you have no control over those sites.~~ In future releases of Lantern, those giving access will be able to ~~manage this aspect as well~~ **limit which sites other people can access via their internet connection**.

What information does Lantern collect about me?
Lantern allows users to choose to provide the Lantern team with useful debugging information as well as analytics, which you can configure in your Lantern settings. If you choose to send Lantern that data, we will not use it for any other purpose other than providing the Lantern service to you and others.

**Note - This is not true for the Valencia version, which always sends the information and doesn't let you disable it.**

**Note - We need to mention that we use 3rd parties that have access to this data.  The old matrix, while slightly outdated and needing some refreshing, is a very useful guide.**

**Comment by chipstehr** [comment]
Ox, thanks a lot for this. My concern is that the level of knowledge required to understand your bullet points is quite high. Most people don't know all the privacy risks when on the Internet, so we are sort of freaking them out by presenting existing problems with the Internet and new problems using Lantern. We wanted to give people reasons to trust Lantern. Saying its "harder" doesn't get at that, though I know we are trying to be clear about safety. I think we need some assertions, reassurances, and a little more black and white (tho this doesn't really exist) rather than warnings, bc users will be dissuaded. Using words like encrypts etc gives people reassurance.

Also, we decided that using the word anonymously is confusing, so we tried to be more clear about it.

Good point about Valencia version. We should create a FAQ about that version...? I am going to give this another go below and then we need to post given that we've launched the Facebook page.

**Comment by chipstehr** [comment]
LANTERN HOME PAGE
An app to end Internet censorship. 
Internet censorship hurts all of us, but we can stop it. Lantern is the app you install on your computer that opens the Internet for everyone.

(Remove Watch Video Link until we have updated video)
DOWNLOAD LANTERN 1.5.17
for
Mac OS X
Available for Mac, Windows, and Linux.
Preview our beta release version ( Version name should be mentioned)

HOW DOES LANTERN WORK?
Lantern is an Internet proxy tool. I’s goal is access: creating fast, reliable connections to the open Internet. Lantern uses secure servers and peer access points to provide Internet access to blocked sites. Lantern is unique because it uses peer connections as a source of Internet connection when servers are unavailable.

QUESTIONS AND ANSWERS
Who Are We?
Lantern is built by the Brave New Software Project, Inc, a registered 501c3 non-profit dedicated to using software to tackle tough global challenges. Brave New Software’s founder and Lantern lead developer, Adam Fisk, was formerly a lead developer of the peer-to-peer file sharing services LimeWire and LittleShoot. While working on these P2P architectures, Adam realized they could be useful in providing unfiltered internet access. You can watch some of Adam’s talks about Lantern here and here.

Is Lantern free? Will running it cost me anything?
Lantern is a free, open source software. It is free to use, modify, and redistribute.
If your Internet connection has a data limit, then giving access through Lantern will be included in your usage.

Is it safe to use Lantern to access the Internet?

For users with blocked Internet:
Encryption: Lantern encrypts all of the information being sent through its secure cloud servers from your computer to the sites on Lantern’s proxy list, so that censors will not be able to see your traffic to those sites. 
HTTPS: Remember to always use use HTTPS and ideally to install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere), because then your traffic is always encrypted and not viewable by anyone regardless of how you are accessing the Internet. 
Cookies + Privacy: Like most proxy tools, Lantern cannot prevent the sites that you visit from using cookies, which store your browsing information in them. Though your traffic is encrypted, Lantern cannot prevent other sites from identifying your IP address or location.
Peer to peer: Whenever the peer-to-peer connections are engaged, Lantern cannot ensure that the traffic is viewed because a censor could actually become a peer. As mentioned before, if you use HTTPS, your traffic will not be viewable by anyone.
IP addresses: If you require that the sites you visit do not learn your IP address or physical location (they typically can, which may come as a surprise), then we recommend you use Tor (link here). 
Which tool for me? In determining which tool to use, if speed and reliability of service are most important to you, Lantern is your tool. If you can tolerate slower speeds to post sensitive information on the Internet, you may want to use Tor. 


Is it Safe for me to use Lantern to provide access to the Internet?
For users with unrestricted Internet access in the uncensored world running as access points, Lantern currently allows other people to access any site on the internet via your connection, including ones that you may disagree with or that may be illegal in your jurisdiction. In future releases of Lantern, those giving access will be able to limit which sites other people can access via their internet connection.


What information does Lantern collect about me?
Lantern allows users to choose to provide the Lantern team with useful debugging information as well as analytics, which you can configure in your Lantern settings. If you choose to send Lantern that data, we will not use it for any other purpose other than providing the Lantern service to you and others.

How does Lantern work if I canʼt reach any users giving access?
To help get the Lantern network started we have set up Lantern Cloud Servers. These channel a significant amount of traffic. This ensures a higher reliability of service by having a variety of sources for Internet access.

What is the Lantern proxied sites list?
Lantern only provides access to blocked sites, and it does this through a default proxied sites list. Therefore, if a web site is unblocked, Lantern will get out of the way and use your regular Internet connection to send you directly to that site. That ensures that users are able to see unblocked content as quickly as possible and also that we don’t waste network resources providing access to content that is not blocked in the first place.
If you are not getting access to a blocked site, that does not necessarily mean that Lantern is not working. You may need to add that site to our list of blocked sites to get access. You can do this in the settings or send an email to us at team@getlantern.org

My Internet isn’t blocked, how I can I help someone who does have blocked Internet? I live in an uncensored region and donʼt know anyone in a censored region. Can I still help?
Definitely! You can both run Lantern and invite more people to join the cause, even if those people also live in an uncensored region. When you run Lantern, you will be added to our DNS round-robin so that a small portion of overall traffic gets routed through your machine. While Lantern also runs its own servers to ensure a good quality of service, each user helps reduce that burden. Our ultimate goal is to build a system that bypasses censorship even if we cease to exist as a company, and that is only possible if a lot of people run it to create new access points. When you invite more people, they will help lighten the load further for everyone.

OK, Iʼve installed Lantern. Now what?
For users in uncensored regions, there are two basic things you can do once youʼve installed Lantern:
— Run Lantern as much as possible.
— Add more users you trust as Lantern friends.
Whenever you run Lantern, you create a new access point users in censored regions can use to access the open Internet. Remember, though, that your own social network is part of what enables Lantern to stay unblocked, so inviting your contacts to join the cause is an important step!

How can I contribute?
Please see Getting Involved.

I have more questions, where do I go?
If you have more technical questions, please see the Developers Q&A. Also feel free to post to the user forums or the developers forum.

**Comment by oxtoacart** [comment]
> Is it safe to use Lantern to access the Internet?

> For users with blocked Internet:

Redundant, can remove

> Encryption: Lantern encrypts all of the information being sent through its secure cloud servers from your computer to the sites on Lantern’s proxy list, so that censors will not be able to see your traffic to those sites.

That's not true.  Lantern encrypts traffic between your computer and the Lantern proxy that's sending your traffic to sites on Lantern's proxied sites list.  If the site doesn't use HTTPS, whoever operates that proxy can see your traffic.  Furthermore, even when using HTTPS, whoever operates those proxies can see which sites you are visiting.  Since we allow anyone to operate peer proxies, the censors can operate peer proxies.  Ergo, the censors can "see your traffic to those sites".

> HTTPS: Remember to always use use HTTPS and ideally to install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere), because then your traffic is always encrypted and not viewable by anyone regardless of how you are accessing the Internet.

Cool.

> Cookies + Privacy: Like most proxy tools, Lantern cannot prevent the sites that you visit from using cookies, which store your browsing information in them. Though your traffic is encrypted, Lantern cannot prevent other sites from identifying your IP address or location.

Not true.  When you use Lantern, the sites that you visit cannot identify your IP address.  Sorry I didn't make that clearer in my edits.

> Peer to peer: Whenever the peer-to-peer connections are engaged, Lantern cannot ensure that the traffic is viewed because a censor could actually become a peer. As mentioned before, if you use HTTPS, your traffic will not be viewable by anyone.

Not sure what "cannot ensure that the traffic is viewed" means.  And again, I don't think the distinction between peer proxies and otherwise is a reasonable one, since we're forcing a portion of all traffic through peer proxies.  This doesn't add anything useful, and at worst can lead to confusion about whether or not Lantern is safe.

> IP addresses: If you require that the sites you visit do not learn your IP address or physical location (they typically can, which may come as a surprise), then we recommend you use Tor (link here). 

Again, Lantern does hide your IP address from the sites that you visit, however it does not hide it from the proxies that are sending your traffic there.

**Comment by oxtoacart** [comment]
Oh, the other thing that I had included in my edits that I think we ought to keep in is that using Lantern opens you to being surveilled by parties which couldn't previously surveil you.

For example, if I wanted to start collecting information about the browsing habits of Lantern users, all I would need to do is set up some peers and start gathering statistics.  I could collect ip addresses, sites visited and content from unencrypted HTTP pages.  I could even mess with the content, for example injecting ads, replacing ads with my own, etc.

To be clear, man-in-the-middle attacks are generally a problem with the internet when you don't use HTTPS, however much like an unencrypted WIFI access point, Lantern creates a new opportunity for 3rd parties to get in the middle of communications to which they otherwise wouldn't have been privy.  That's an important point that I think shouldn't get lost.

**Comment by chipstehr** [comment]
Is it safe to use Lantern to access the Internet?

For users with blocked Internet:
Redundant, can remove

Encryption: Lantern encrypts all of the information being sent through its secure cloud servers from your computer to the sites on Lantern’s proxy list, so that censors will not be able to see your traffic to those sites.
That's not true. Lantern encrypts traffic between your computer and the Lantern proxy that's sending your traffic to sites on Lantern's proxied sites list. If the site doesn't use HTTPS, whoever operates that proxy can see your traffic. Furthermore, even when using HTTPS, whoever operates those proxies can see which sites you are visiting. Since we allow anyone to operate peer proxies, the censors can operate peer proxies. Ergo, the censors can "see your traffic to those sites".

---> I thought by using "cloud servers" we were being clear that this is not when using peers. Since we operate those proxies, I thought its as secure as can be. But I see your point about always having peers in the mix so it not being a useful explanation. But I need to give some assurance...?

HTTPS: Remember to always use use HTTPS and ideally to install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere), because then your traffic is always encrypted and not viewable by anyone regardless of how you are accessing the Internet.
Cool. --> Is this true? I thought you said its still viewable?

Cookies + Privacy: Like most proxy tools, Lantern cannot prevent the sites that you visit from using cookies, which store your browsing information in them. Though your traffic is encrypted, Lantern cannot prevent other sites from identifying your IP address or location.
Not true. When you use Lantern, the sites that you visit cannot identify your IP address. Sorry I didn't make that clearer in my edits.

---> Okay will include.

Peer to peer: Whenever the peer-to-peer connections are engaged, Lantern cannot ensure that the traffic is viewed because a censor could actually become a peer. As mentioned before, if you use HTTPS, your traffic will not be viewable by anyone.
Not sure what "cannot ensure that the traffic is viewed" means. And again, I don't think the distinction between peer proxies and otherwise is a reasonable one, since we're forcing a portion of all traffic through peer proxies. This doesn't add anything useful, and at worst can lead to confusion about whether or not Lantern is safe.

IP addresses: If you require that the sites you visit do not learn your IP address or physical location (they typically can, which may come as a surprise), then we recommend you use Tor (link here).
Again, Lantern does hide your IP address from the sites that you visit, however it does not hide it from the proxies that are sending your traffic there. 

--> Okay will include. If you can give me something for the first issue as an assurance, I will redraft with shorter answers and add a read more.

**Comment by oxtoacart** [comment]
> ---> I thought by using "cloud servers" we were being clear that this is not when using peers. Since we operate those proxies, I thought its as secure as can be. But I see your point about always having peers in the mix so it not being a useful explanation. But I need to give some assurance...?

Oops.  Yeah, I'd say that if I didn't notice the distinction, our users probably won't either :)

> Cool. --> Is this true? I thought you said its still viewable?

You're right that there are cases where some parties (your employer, the censors) have the ability to forge certificates, in which case HTTPS is not secure, however as a general rule HTTPS is pretty good.  And Lantern actually improves things by not accepting forged certificates.

> --> Okay will include. If you can give me something for the first issue as an assurance, I will redraft with shorter answers and add a read more.

I guess I'm not sure what assurances to give.  As long as we include random domain-fronted peers in our system, you're overall probably slightly less secure using Lantern than you are using the open internet.  Now, if we exclude peers, we have a much better story, namely that Lantern makes you more secure on Wifi, corporate and censored networks.

BTW, to put peers into perspective - we currently have a little over 20 registered peers online.

**Comment by chipstehr** [comment]
Exactly that's why I thought it was important to stress that most of our
stuff is done through cloud servers that we manage. The security is high bc
few peers are in rotation.

For number one then I'm going to continue to use the original language and
the majority of servers are managed by Lantern.

**Comment by oxtoacart** [comment]
> The security is high bc few peers are in rotation.

Not really.  We randomly distribute traffic amongst all servers and peers, so even though peers only get a small percentage of your traffic, over time they will still see a lot of your traffic.  Assuming that you tend to visit the same sites over and over and that the malicious peers remain online long enough, they can get a pretty good picture of your browsing behavior.

**Comment by chipstehr** [comment]
LANTERN HOME PAGE
An app to end Internet censorship. 
Internet censorship hurts all of us, but we can stop it. Lantern is the app you install on your computer that opens the Internet for everyone.

(Remove Watch Video Link until we have updated video)
DOWNLOAD LANTERN 1.5.17
for
Mac OS X
Available for Mac, Windows, and Linux.
Preview our beta release version ( Version name should be mentioned)

HOW DOES LANTERN WORK?
Lantern is an Internet proxy tool. It’s goal is access: creating fast, reliable connections to the open Internet. Lantern uses secure servers and peer access points to provide Internet access to blocked sites. Lantern is unique because it uses peer connections as a source of Internet connection when servers are unavailable.

QUESTIONS AND ANSWERS
Who Are We?
Lantern is built by the Brave New Software Project, Inc, a registered 501c3 non-profit dedicated to using software to tackle tough global challenges. Brave New Software’s founder and Lantern lead developer, Adam Fisk, was formerly a lead developer of the peer-to-peer file sharing services LimeWire and LittleShoot. While working on these P2P architectures, Adam realized they could be useful in providing unfiltered internet access. You can watch some of Adam’s talks about Lantern here and here.

Is Lantern free? Will running it cost me anything?
Lantern is a free, open source software. It is free to use, modify, and redistribute.
If your Internet connection has a data limit, then giving access through Lantern will be included in your usage.


Is it safe to use Lantern to access the Internet?

Your Internet surfing is relatively safe with Lantern but it’s important to remember:
	•	HTTPS: Remember to always use use HTTPS and ideally to install the HTTPS Everywhere browser extension (https://www.eff.org/https-everywhere), because then your traffic is always encrypted and not viewable by anyone regardless of how you are accessing the Internet. As an added bonus Lantern doesn’t allow for false HTTPS certificates.
	•	Peers: A portion of all Lantern traffic is handled by peer proxies.  It is possible for censors and other untrusted 3rd parties to run these peer proxies.  You can prevent them from viewing the content of your traffic by using HTTPS, though the sites that you visit will be viewable by them.
	•	Cookies + Privacy: Lantern does prevent other sites from seeing your IP, though it cannot prevent proxies (either peers or cloud servers) from seeing your IP. 
	•	IP addresses: If you require that no one sees your IP address or physical location (they typically can, which may come as a surprise), then you might have a better chance in improving your privacy with Tor. https://www.torproject.org
	•	Which tool for me? In determining which tool to use, if speed and reliability of service are most important to you, Lantern is your tool. If you can tolerate slower speeds to post sensitive information on the Internet, you may want to use Tor. 


Is it Safe for me to use Lantern to provide access to the Internet?
For users with unrestricted Internet access in the uncensored world running as access points, Lantern currently allows other people to access any site on the internet via your connection, including ones that you may disagree with or that may be illegal in your jurisdiction. In future releases of Lantern, those giving access will be able to limit which sites other people can access via their internet connection.

Is it Safe for me to use Lantern to provide access to the Internet?
For users with unrestricted Internet access in the uncensored world running as access points, Lantern currently allows other people to access any site on the internet via your connection, including ones that you may disagree with or that may be illegal in your jurisdiction. In future releases of Lantern, those giving access will be able to limit which sites other people can access via their internet connection.


What information does Lantern collect about me?
Lantern allows users to choose to provide the Lantern team with useful debugging information as well as analytics, which you can configure in your Lantern settings. If you choose to send Lantern that data, we will not use it for any other purpose other than providing the Lantern service to you and others.

How does Lantern work if I canʼt reach any users giving access?
To help get the Lantern network started we have set up Lantern Cloud Servers. These channel a significant amount of traffic. This ensures a higher reliability of service by having a variety of sources for Internet access.

What is the Lantern proxied sites list?
Lantern only provides access to blocked sites, and it does this through a default proxied sites list. Therefore, if a web site is unblocked, Lantern will get out of the way and use your regular Internet connection to send you directly to that site. That ensures that users are able to see unblocked content as quickly as possible and also that we don’t waste network resources providing access to content that is not blocked in the first place.
If you are not getting access to a blocked site, that does not necessarily mean that Lantern is not working. You may need to add that site to our list of blocked sites to get access. You can do this in the settings or send an email to us at team@getlantern.org

My Internet isn’t blocked, how I can I help someone who does have blocked Internet? I live in an uncensored region and donʼt know anyone in a censored region. Can I still help?
Definitely! You can both run Lantern and invite more people to join the cause, even if those people also live in an uncensored region. When you run Lantern, you will be added to our DNS round-robin so that a small portion of overall traffic gets routed through your machine. While Lantern also runs its own servers to ensure a good quality of service, each user helps reduce that burden. Our ultimate goal is to build a system that bypasses censorship even if we cease to exist as a company, and that is only possible if a lot of people run it to create new access points. When you invite more people, they will help lighten the load further for everyone.

OK, Iʼve installed Lantern. Now what?
For users in uncensored regions, there are two basic things you can do once youʼve installed Lantern:
— Run Lantern as much as possible.
— Add more users you trust as Lantern friends.
Whenever you run Lantern, you create a new access point users in censored regions can use to access the open Internet. Remember, though, that your own social network is part of what enables Lantern to stay unblocked, so inviting your contacts to join the cause is an important step!

How can I contribute?
Please see Getting Involved.

I have more questions, where do I go?
If you have more technical questions, please see the Developers Q&A. Also feel free to post to the user forums or the developers forum.

**Comment by oxtoacart** [comment]
LGTM!

**Comment by atavism** [comment]
> Lantern is an Internet proxy tool. It’s goal is access: creating fast, reliable connections to the open Internet. Lantern uses secure servers and peer access points to provide Internet access to blocked sites. Lantern is unique because it uses peer connections as a source of Internet connection when servers are unavailable.

I'm not sure about this last sentence, particularly this phrase:  "peer connections as a source of Internet connection" -- how about "uses peer connections as a source of Internet connectivity when servers are unavailable" instead?

**Comment by chipstehr** [comment]
Good. I'll ask Todd to make the change.

**Comment by atavism** [comment]
> Good. I'll ask Todd to make the change.

This is Todd :) Which version do you prefer?

**Comment by chipstehr** [comment]
For that starter para you can use your version Todd,

Lantern is an Internet proxy tool. It’s goal is access: creating fast, reliable connections to the open Internet. Lantern uses secure servers and peer access points to provide Internet access to blocked sites. Lantern is unique because it uses peer connections as a source of Internet connectivity when servers are unavailable.

**Comment by chipstehr** [comment]
Sorry Todd for a second I confused you with Alan.

You can use your suggestion

Lantern is an Internet proxy tool. It’s goal is access: creating fast,
reliable connections to the open Internet. Lantern uses secure servers and
peer access points to provide Internet access to blocked sites. Lantern is
unique because it uses peer connections as a source of Internet
connectivity when servers are unavailable.

**Comment by atavism** [comment]
@chipstehr Thanks! What videos should I link to in the "Who Are We?" section?

**Comment by atavism** [comment]
@chipstehr The new text is available to preview here: http://192.241.213.146/index.html I tried to preserve the ordering you indicated. Did you want the previous FAQ entries removed that you didn't specify above?

**Comment by oxtoacart** [comment]
Looks nice!  Can you please turn the reference to HTTPS everywhere into a link?

**Comment by atavism** [comment]
> Looks nice! Can you please turn the reference to HTTPS everywhere into a link?

Done!

**Comment by atavism** [comment]
> You can watch some of Adam’s talks about Lantern here and here.

I still need the videos I'm actually supposed to link to here before I can deploy the changes and push the new strings to Transifex.

**Comment by atavism** [comment]
@myleshorton Just curious: are we planning to update the beta release channel to point to the new version of Lantern on the website?
